export let Page = 0;

export const Data = {
  page1: {
    words: [
      'Dismal',
      'Gloom',
      'Incensed',
      'Incite',
      'Detrimental',
      'Blatant',
      'Condemned',
      'Sequel',
      'Lacklustre',
      'Paraphrase',
      'Outmoded',
      'Prodiguous',
      'Assertions',
      'Scrutiny',
      'Notoriety',
      'Flamboyant',
      'Exuberance',
      'Peruse',
    ],
    meanings: [
      'Causing a state of gloom or depression',
      'A state of depression',
      'extremely angry but not necessarily incited to action',
      'encourage',
      'tending to cause harm',
      'done openly and unashamedly',
      'officially declared unfit for use',
      'Something that takes place after or as a result of an earlier event',
      'Lacking in vitality, force ir conviction',
      'express meaning of something using different words, especially to achieve greater clarity',
      'old-fashioned',
      'impressively great in extent , size or degree',
      'a confident and forceful statement of fact or belief',
      'critical observation or examination',
      'state of being famous',
      'a person who attracts attention cause of their exuberance, condifence or stylishnes',
      'Quality of being full of energy',
      'Read carefully',
    ],
    count: 18,
  },

  page2: {
    words: [
      'Obscure',
      'Magnanimous',
      'Ambivalent',
      'Condemnatory',
      'Bequeathed',
      'Heuristic',
      'Reverberate',
      'Bemoaning',
      'Commending',
      'Enjoining',
      'Subtle',
      'Allure',
      'Pedantic',
      'Contemptuous',
      'Edify',
      'Preclude',
      'Jingoism',
      'Belligerent',
      'Restive',
      'Restiveness',
      'Euphoria',
      'Cupidity',
      'Extant',
      'Moot',
      'Fallacious',
    ],
    meanings: [
      'Not known/Not discovered',
      'generous or forgiving',
      'having mized or contradictory feelings',
      'Expressing strong disapproval',
      'Pass on or leave something to someone',
      'Enabing someone to discover something',
      'Having continuing and serious effects',
      'Express discontent or sorrow',
      'Praise formally',
      'urge to do something',
      'so delicate or precise as to be difficult to analyze or describe',
      'quality of being powerful',
      'excessively concerned with minor details/ marked by focus on trivial aspects',
      'feeling that a person/thing is below consideration',
      'imporve morally/intellectually',
      'prevent from happening',
      'attitude of blind nationalism',
      'hostile anf agressive',
      'unable to remain still',
      'stubbornly resisting',
      'state of excitement or happiness',
      'greed for money or posessions',
      'surviving',
      'uncertainity',
      'based on a mistaken belief',
    ],
    count: 25,
  },
  page3: {
    words: [
      'Topical',
      'Retroactive',
      'Stratification',
      'Tyrranical',
      'Veracious',
      'Intimate',
      'Wanting',
      'Mercurical',
      'Acrimony',
      'Castigate',
      'Reprimand',
      'Chastise',
      'Venality',
      'Galvanize',
      'Harangue',
      'Egregious',
      'Parasimonious',
      'Frugal',
      'Belie',
      'Enervate',
      'Sap',
      'Venerate',
      'Vindicate',
    ],
    meanings: [
      'Immediate relevance',
      'Taking effect from a date in the past',
      'classification into different groups',
      'exercising power in a cruel way',
      'truthful',
      'to suggest something subtly',
      'lacking',
      'prone to unexpectedness and unpredictable changes in mood',
      'bitterness and ill will',
      'to reprimand harshly',
      'a formal expression of disapproval',
      'to reprimand harshly',
      'condition on being susceptible to bribes or corruption',
      'to excite or inspire',
      'a long pompous speech',
      'standing out in a negative way',
      'extremely frugal: miserly',
      'economical',
      'to give a false representation or misrepresent',
      'to sap energy from',
      'weaken or destroy',
      'to respect deeply',
      'clear of accusation, blame Or suspicion or doubt with supporting arguments or proof',
    ],
    count: 23,
  },
  page4: {
    words: [
      'Rubric',
      'Thesis',
      'Premise',
      'Err',
      'Tangible',
      'Perceptible',
      'Plausible',
      'Concision',
      'Eloquent',
      'Connotation',
      'Insidious',
      'Profound',
      'Insubstantial',
      'Transient',
      'Gaffes',
      'Uncouth',
      'Imprudent',
      'Opportune',
      'Pervasive',
      'Bereft',
    ],
    meanings: [
      'A set of instructions or rules',
      'A statement or theory that is put forward as a premise to be maintained or proved',
      'A previous statement or proposition',
      'Make a mistake',
      'Perceptible by touch',
      '(Especially a slight movement or change of state) able to be seen or noticed',
      'Seeming reasonable/probable',
      'quality or state of being concise',
      'fluent/persuasive in speaking/writing',
      'an idea/feeling which a word invokes for a person in addition to its literary/primary meaning',
      'proceeding as a gradual subtle way, but with harmful effects',
      'intense/deep',
      'lacking strength and solidity (also insignificant)',
      'Lasting for a short time; impermanent',
      'an unintentional act or remark causing embarrasment to its originator',
      'lacking good manners, refinement or grace',
      'not showing care for the conseuences of an action',
      'convenient/appropriate',
      'spread widely throughout an area',
      'Deprived, (sad and lonely, especially through someones death or departure',
    ],
    count: 20,
  },
  page5: {
    words: [
      'Implausible',
      'Imperceptible',
      'Sporadic',
      'Incredulously',
      'Congenial',
      'Angst',
      'Indignation',
      'Camaraderie',
      'Belie',
      'Embezzlement',
      'Discrepancies',
      'Extravagance',
    ],
    meanings: [
      'Not reasonable or probable',
      'So slight, gradual or subtle, that it seems not to be preceived',
      'occuring at irregular intervals or only in a few places; scattered or isolated',
      'unwilling or unable to believe something',
      'pleasing or liked on account of having similar qualities and interests',
      'persistent worry',
      'anger cause of unfair treatment',
      'mutual trust and friendship among people who spend a lot of time together',
      'fail to give a true impression of something',
      'theft or misappropriation of funds placed in ones trust or belongings to ones employer',
      'an illogical or surprising lack of compatibility or similarity between 2 or more facts',
      'lack of restraint in spending money or using resources; a things on which too much money has been spent; excessive elaboration',
    ],
    count: 12,
  },
  page6: {
    words: [
      'Pilfering',
      'oversight',
      'ruse',
      'ploy',
      'globetrotter',
      'Antithetical',
      'Veritable',
      'Germane',
      'Forbidding',
      'Forbid',
      'Ornate',
      'Aphorism',
      'Pithy',
      'Intrepid',
      'Bushwackers',
      'Eminence',
      'Temperance',
      'Abstinence',
      'Tumultuos',
      'Providential',
      'Dispassionate',
      'Precariously',
      'Orthodox',
    ],
    meanings: [
      'Steel',
      'An unintentional failure to notice or do something; the action of overseeing something',
      'An action to decieve or trick someone',
      'A cunning plan to turn a situation to ones advantage',
      'A person who travels widely',
      'Directly opposed or contrasted; mutually incompatible',
      'Used for emphasis',
      'relevant to a subject under consideration',
      'Unfriendly or threatening in appearance',
      'refuse to allow',
      'elaborated or highly decorated',
      'a pithy observation of a general truth',
      'vigorously expressive',
      'fearless or adventurous',
      'a person who travels around or lives in thinly populated woodlands',
      'fame or acknowledged superiority',
      'abstinence from alcoholic drink',
      'the practice of restraining oneself from indulging in something; typically alcohol or sex',
      'excited, confused, or disorderly',
      'opportune',
      'not influenced by strong emotion, and hence be rational and impartial',
      'not securely held in position; likely to collapse',
      'following or conforming to tradition or rules',
    ],
    count: 23,
  },
  page7: {
    words: [
      'eccentric',
      'trifling',
      'conventional',
      'ameliorate',
      'ascertain',
      'exacerbate',
      'harbringers',
      'prophetic',
      'monotonous',
      'typical',
      'stark',
      'rife',
      'apathy',
      'affability',
      'allegation',
      'phony',
      'incongruous',
      'harmony',
      'concord',
      'symphony',
      'fortuitous',
      'warring',
      'presumptive',
      'sham',
      'purported',
    ],
    meanings: [
      'slightly strange',
      'unimportant or trivial',
      'in accordance with what is believed',
      'make something better',
      'make sure of',
      'make a problem worse',
      'a person/thing that announces or signals its arrival',
      'accurately predicting what will happen in the future',
      'dull, tedious, repetitive',
      'showing characteristics that were expected or popularly associated with a particular person/thing',
      'unpleasantly or sharply clear',
      'full of or widespread',
      'lack of interest, enthusias, or concern',
      'quality of having a friendly, and good-natured manner',
      'a claim or assertion that someone has done something illegal or wrong without proof',
      'not genuine or fraudulent',
      'not in harmony or keeping with surroundings or other aspects of something',
      'state of being in agreement or concord',
      'agreement',
      'something regarded as a composition of different elements',
      'happening by chance',
      'in conflict with each other',
      'presumed in absence of further information',
      'a thing that is not what it is purported to be',
      'appearing or stating to be true; not alleged',
    ],
    count: 25,
  },
  page8: {
    words: [
      'stance',
      'deceitful',
      'prodigy',
      'preternatural',
      'conductor',
      'dichotomy',
      'milieu',
      'rhetoric',
      'rhetorical',
      'elicit',
      'explicit',
      'acumen',
      'reverence',
      'fastidious',
      'didactic',
      'iconoclast',
      'polemic',
      'disseminate',
      'deem',
      'erroneous',
      'capricious',
    ],
    meanings: [
      'attitude of a person or organization towards a standpoint; a way in which someone stands',
      'deceiving or misleading others; guilty of involving in deceit',
      'an outstanding example of a particular quality',
      'beyond what is normal or natural',
      'a person who directs performance of an orchestra',
      'a divison or contrast between two things that are represented as being opposed',
      'a persons social environment',
      'language desinged to have a persuasive effect',
      'asked in order to make a statement rather than elicit information',
      'evoke or draw out',
      'stated clearly or in detail',
      'the ability to male good judgements and take quick decision',
      'deep respect for someone or something',
      'very attentive to and concerned about accuracy and detail',
      'intended to teach, particularly in having moral instruction as an ulterior motive',
      'a person who attacks or criticizes cherished beliefs and institutions',
      'a strong verbal or written attack on someone or something',
      'spread widely',
      'regard or consider in a specific way',
      'wrong',
      'given to sudden and unaccontable changes in mood or behavior',
    ],
    count: 21,
  },
  page9: {
    words: [
      'corroborate',
      'debunking',
      'bogus',
      'novel',
      'obsolete',
      'contemporary',
      'contemporaries',
      'copious',
      'acerbic',
      'scathing',
      'scornful',
      'contempt',
      'derision',
      'miserliness',
      'stingy',
      'diffidence',
      'thrift',
      'novice',
      'agonizing',
      'meticulous',
      'convoluted',
      'avid',
      'tenuous',
      'florid',
      'intricate',
    ],
    meanings: [
      'confirm or give support to',
      'expose the falseness or hollowness of (an idea/belief),',
      'not genuine or true',
      'interestingly new or unusual',
      'outdated',
      'living or occuring at the same time',
      'a person or thing exisiting at the same time as others',
      'abundant in supply or quantity',
      'sharp or forthright',
      'severly critical',
      'feeling or expressing contempt or derision',
      'contemptuous',
      'contemptuous ridicule or mockery',
      'excessive desire to save money',
      'mean; ungenerous',
      'modesty or shyness cause of lack of self-confidence',
      'quality of using money and other resources carefully and not wastefully',
      'a person new to and inexperienced in a job/situation',
      'causing great physical or mental pain',
      'showing great attention to detail, careful and precise',
      'extremely complex, and difficult to solve',
      'having or showing a keen interest or enthusiasm in something',
      'very weak or slight',
      'excessively intricate or elaborate or having a red flushed complexion',
      'very complicated or detailed',
    ],
    count: 25,
  },
  page10: {
    words: [
      'egalitarian',
      'fluid',
      'ephermal',
      'intelligible',
      'inordinate',
      'plutocrat',
      'upheavel',
      'apprehension',
      'forethought',
      'wariness',
      'tranquil',
      'cynical',
      'disquiet',
      'endorse',
      'injudicious',
      'imperious',
      'unsparing',
      'frivolity',
      'disposition',
    ],
    meanings: [
      'believing in or based on the principle that all people are equal and deserve equal rights and opportunities',
      'smoothly elegant or graceful; unstable or able to change',
      'lasting for a very shor time',
      'able to be understood; comprehensible',
      'unusually or disproportionately large; excessive',
      'a person whose power derives from their wealth',
      'a violent or sudden change or disruption to something',
      'anxiety or feat that something bad might happen; action of arresting someone',
      'careful consideration of what will be necessary or may happen in the future',
      'caution about possible dangers or problems',
      'calm',
      'believing that people are motivated purely by self-interest (other meanings too, check book)',
      'a feeling of worry or unease',
      'recommend or approval',
      'showing very poor judgement; unwise',
      'arrogant or domineering',
      'merciless or severe',
      'lack of seriousness; light-heartedness',
      'inclination or tendency (not sure, check book)',
    ],
    count: 19,
  },
  page11: {
    words: [
      'penitential',
      'penance',
      'repentance',
      'intractable',
      'prolix',
      'impetuous',
      'prodigal',
      'lavish',
      'sumptuous',
      'taciturn',
      'volubility',
      'pellucid',
      'extraneous',
      'eclipse',
      'bolster',
      'hotly',
    ],
    meanings: [
      'relating to or expressing penance',
      'punishment inflicted on oneself as an outward expression of wrongdoing',
      'sincere regret or remorse',
      'hard to control or deal with',
      'using too many words; tediously lengthy',
      'acting or done quickly without thought or care',
      'spending money or resources recklessly',
      'sumptuously rich, elaborate, or luxurious',
      'splendid and expensive looking',
      'reserved or uncommunicative in speech',
      'quality of talking fluently, talktativenss',
      'transculently clear',
      'irrelevant to the subject being dealth with',
      'a loss of significance or power',
      'support or strengthen',
      'in a passionate, intense or angry way',
    ],
    count: 16,
  },
  page12: {
    words: [
      'ruminate',
      'prosaic',
      'hackneyed',
      'shore up',
      'besieged',
      'electorate',
      'aloof',
      'conspicuous',
      'placid',
      'skittish',
      'vociferous',
      'vehement',
      'fortuitous',
      'indecorous',
      'propriety',
      'unseemly',
      'prevailing',
      'recalcitrant',
      'obstinate',
      'annul',
      'substantiate',
    ],
    meanings: [
      'think deeply about something',
      'lacking imaginativeness or originality; commonplace, unromantic',
      'overused',
      'support',
      'surrounded by armed forces aiming to capture it or to force surrender',
      'all people in a country who are eligible to vote',
      'not friendly; conspicuously involved',
      'clearly visible, or attracting attention',
      'calm and peaceful, not easily excited',
      'playfully unpredictable or frivolous',
      'expressing by vehement opinions',
      'showing strong feelings; forceful, passionate or intense',
      'happening by chance rahter than intention',
      'not in keeping with good taste and propriety',
      'conformity to conventionally accepted standards',
      'not proper or not appropriate',
      'exisitng at a particular time',
      'having an obstinately uncooperative attitude towards authority or discipline',
      'stubbornly refusing to change ones opinion or chosen course of action despite attempts to persuade one to do so',
      'declaring of no existence',
      'provide evidence to support or prove truth',
    ],
    count: 21,
  },
  page13: {
    words: [
      'coarse',
      'oblivious',
      'genteel',
      'discern',
      'retort',
      'cryptic',
      'demeanor',
      'meek',
      'disdainful',
      'repudiation',
      'repression',
      'subduing',
      'entail',
      'deluge',
      'inkling',
      'hindsight',
      'diligent',
      'subjugate',
      'obeisance',
      'deferential',
      'incontrovertible',
      'disputed',
    ],
    meanings: [
      'rough or hard',
      'clueless',
      'characterized by exaggerated or affected politeness',
      'recognize',
      'say something in an answer to a remark; typically in a sharp, angry manner',
      'having a meaning that is mysterious or obscure',
      'outward behavior',
      'submissive, quite and gentle',
      'showing contempt or lack of respect',
      'rejection of a proposal or idea',
      'action of subduing someone or something by force',
      'overcome, or bring under control by force',
      'involve as a necessary or inevitable part of a consequence',
      'a great quantity of something arriving at the same time',
      'a slight knowledge or suspicion',
      'understanding os a situation only after it has happened',
      'having or showing care in ones work of duties',
      'bring under dominion of control',
      'deferential respect',
      'respectful',
      'not able to be denied or disputed',
      'resisted, also question if it is valid',
    ],
    count: 22,
  },
  page14: {
    words: [
      'equivocal',
      'diminutive',
      'sacerdotal',
      'posterity',
      'relegate',
      'sublimate',
      'apogee',
      'nadir',
      'consensus',
      'intuition',
      'cognizant',
      'apocryphal',
      'botched',
      'bandy',
      'eschew',
      'deliberately',
      'elusive',
      'ironclad',
      'ostensibly',
      'disparate',
      'anecdote',
      'anecdotal',
      'prolific',
      'ardent',
      'boycotter',
    ],
    meanings: [
      'open to more than one interpretation',
      'extremely or unusually small',
      'relating to priests or priesthood',
      'all future generations of people',
      'assign an inferior rank or position',
      'tranform into a pure or idealized form',
      'highest point in the development of something',
      'lowest or most unsuccessful point in a situation',
      'a general agreement',
      'ability to understand something instinctively, without the need for conscious reading',
      'having knowledge or awareness',
      'of doubtful authenticity, although widely circulated as being true',
      '(of a task) carried out badly or carelessly',
      'pass on or discuss in a casual or uninfomed way',
      'deliberately avoid using, or stay away from',
      'on purpose',
      'difficult to find, catch or achieve',
      'impossible to contradict, weaken or change',
      'as appears or is stated to ne true, although not necessarily',
      'essentially different in kind, not able to be compared',
      'a short interesting story of a person',
      'not necessarily true, because based on personal accounts rather than facts or research',
      'present in large quantities',
      'very enthisiastic or passionate',
      'run away to live without social relations',
    ],
    count: 25,
  },
  page15: {
    words: [
      'indelible',
      'fleeting',
      'railing',
      'adverse',
      'bode',
      'portent',
      'mete',
      'transgression',
      'inured',
      'ostentatious',
      'agog',
      'offing',
      'plight',
      'affability',
      'boorishness',
      'heyday',
      'precipituous',
      'entice',
      'thwart',
      'obsolete',
      'impregnable',
      'jarring',
      'incongruous',
      'affable',
      'morose',
      'sullen',
      'aloof',
      'jubilant',
    ],
    meanings: [
      'not able to be forgotten',
      'lasting for a very short time',
      'complain or protest strongly',
      'preventing success or development; harmful',
      'be a portent of a particular outcome',
      'future significance',
      'dispense or allot justice, a punishment',
      'an act that goes against law, rules etc',
      'accustom to something especially something unpleasant',
      'designed to impress',
      'very eager or curious to hear or see something',
      'likely to happen or appear soon',
      'a dangerous, difficuly or unfortunate situation',
      'quality of having a friendly, and good natured manner',
      'rough and bad mannered',
      'the period of a person or things greatest success or popularity',
      ' done suddenly without consideration',
      'attract or tempt by offering pleasure or advantage',
      'prevent from accomplishing something',
      'outdated',
      'unable to capture or break into',
      'incongruous in a striking or shocking way',
      'not in harmony or keeping with surroundings or other aspects of something',
      'friendly, good natured or easy to talk to',
      'sullen and ill-tempered',
      'bad-tempered',
      'not friendly and forthcoming',
      'feeling or expressing great happiness and triumph',
    ],
    count: 28,
  },
  page16: {
    words: [
      'dissent',
      'robust',
      'knack',
      'abstruse',
      'revere',
      'pellucid',
      'inscrutable',
      'unsolicited',
      'countermand',
      'overt',
      'nettlesome',
      'reticent',
      'sycophantic',
      'obsequious',
      'elusive',
      'propensity',
      'dubious',
      'misconstrue',
      'conflate',
      'disjointed',
      'languishing',
      'vociferous',
      'deride',
      'trumpted',
      'proclaim',
      'condone',
      'foil',
    ],
    meanings: [
      'holding opinions at variance with those of officially held',
      'strong and healthy',
      'an acquired or natural skill to do something',
      'difficuly to understand; obscure',
      'feel deep respect or admiration for something',
      'translucently clear',
      'impossible to understand or interpret',
      'not asked for',
      'revoke or cancel',
      'done or shown openly, plainly apparent',
      'causing annoyance or difficulty',
      'not revealing ones thoughts or feelings readily',
      'behaving or done in an obsequious way in order to gain advantage',
      'obedient or attractive to an excessive degree',
      'difficult to find, catch or achieve',
      'a natural tendency to behave in a particular way',
      'hesitating or doubting',
      'interpret wrongly',
      'combine into one',
      'lacking a coherent sequence of connection',
      'failing to make progress or be successful',
      'expressing by vehemnt opinions, loud and forceful',
      'express contempt for',
      'proclaim widely or loudly',
      'claim officially',
      'accept something which is morally wrong',
      'prevent from succeeding',
    ],
    count: 27,
  },
  page17: {
    words: [
      'equivocation',
      'embellishment',
      'canopy',
      'foliage',
      'indigeneous',
      'veritable',
      'veteran',
      'cornucopia',
      'glean',
      'purge',
      'toil',
      'incessant',
      'candid',
      'tenacious',
      'reconcile',
      'revelation',
      'subvert',
      'amenable',
      'burgeon',
      'paean',
      'prognosis',
    ],
    meanings: [
      'use of ambigious language to conceal truth or to avoid commiting oneself',
      'a detail, especially one that is untrue, added to a story to spice it up',
      'uppermost brancehs of tree, forming a continuous layer of foliage',
      'plant leaves collectively',
      'native',
      'used for emphasis',
      'person with long experience in a particular field',
      'an abundant supply of good things of a specified kind',
      'obtain from various sources; often with difficulty',
      'rid of an unwanted quality',
      'work extremely hard or incessantly',
      'continuing without pause or interruption',
      'truthful and straight forward; frank',
      'tending to keep a firm hold of something',
      'make to show to be compaitble',
      'a suprising or unknown fact that has been disclosed to others',
      'undermine power and authority',
      'open and responsive to suggestion',
      'increasing rapidly',
      ' a creative work expressing enthusiastic praise',
      'forecast of a likely outcome',
    ],
    count: 21,
  },
  page18: {
    words: [
      'skeptic',
      'spur',
      'stymie',
      'tractable',
      'incendiary',
      'tarnish',
      'idylls',
      'rambling',
      'torrid',
      'exorcise',
      'foreshadow',
      'aristocracy',
      'inimical',
      'apotheosis',
      'vicissitudes',
      'inextricably',
      'supplant',
      'supersede',
      'circumvent',
      'mollify',
      'rile',
      'prevaricate',
      'evasive',
      'laconic',
      'ingenuous',
    ],
    meanings: [
      'a person inclined to question or doubt accpeted opinions',
      'urge forward',
      'prevent or hinder progress of',
      'easy to control or influence',
      'tending to stir up conflict',
      'make or become less valuable',
      'an extremely happy. peaceful period or a situation',
      'lengthy and confused or inconsequential',
      'very hot and dry; full of passion arising from sexual love',
      'get rid of',
      'be a warning or indication of a future event',
      'highest class in certain societies',
      'tending to obstruct or harm',
      'highest point in development of something',
      'a change of circumstances or fortune typically one that in unpleasant',
      'in a way that is impossible to separate',
      'replace or supersede',
      'take place of',
      'find a way around',
      'apease the anger or anxiety of someone',
      'make someone angry',
      'speak out in an evasive way',
      'tending to avoid commitment',
      'using very few words',
      'naive and innocent',
    ],
    count: 25,
  },
  page19: {
    words: [
      'parochial',
      'censure',
      'aberration',
      'calumny',
      'gregarious',
      'demur',
      'profligate',
      'innocuous',
      'upbraid',
      'reproach',
      'commensurate',
      'prevaricate',
      'impertinent',
      'anorphous',
      'anomalous',
      'dystopia',
      'conjure',
      'vivid',
      'totalitarian',
      'synoptic',
      'apolitical',
      'macabre',
      'picturesque',
      'tantamount',
      'reversion',
      'heresy',
    ],
    meanings: [
      'narrowly restricted in scope or outlook',
      'to express strong disapproval',
      'a deviation from what is normal or expected',
      'making a false statement meant to injure a persons reputation',
      'likely to socialize with others',
      'to object or show reluctance',
      'spending resources recklessly or wastefully',
      'harmless and doesnt produce ill effects',
      'to scold or reproach',
      'express ones disapproval or disappointment',
      'to be in proportion or corresponding in degree or amount',
      'to speak in an evasive way',
      'being disrespectful, improperly forward or bold',
      'shapeless',
      'not normal',
      'an imagined state or society where there is a great suffering or injustice; typically a post apocalyptic one',
      'cause to appear',
      'producing powerful feelings or strong, clear images in mind',
      'relating to a system os government that is centralized or dictatorial',
      'forming a general summary',
      'not interested/involved in politics',
      'disturbing because concerned with or causing a fear of death',
      'visually attractive',
      'virtually same as',
      'return to previous state',
      'belief or opinion in contrary to orthodox religious; opinion profoundly at odds with what is accepted',
    ],
    count: 26,
  },
  page20: {
    words: [
      'vanquish',
      'lionize',
      'ostracize',
      'luminary',
      'canon',
      'champion',
      'entrenched',
      'unequivocal',
      'happenstance',
      'aptitude',
      'reprehensible',
      'censure',
      'stem from',
      'hinged upon',
      'glib',
      'platitude',
      'succor',
      'pat',
      'evocative',
      'heady',
      'exhilarating',
      'elated',
      'ecstatic',
      'halcyon',
      'accretion',
      'underscore',
      'squander',
      'probing',
      'ingenuity',
      'sedulous',
    ],
    meanings: [
      'defeat thoroughly',
      'treat as a celebrity',
      'exclude from a society or group',
      'a person who inspires or influences others, especially one prominent in a particular sphere',
      'a general rule, law, principle by which something is judged',
      'vigorously support or defend the cause of',
      'firmly establish or defend the cause of',
      'leaving no doubt',
      'coincidence',
      'natural ability to do something',
      'deserving censure or condemnation',
      'severe disapproval',
      'to be cause by',
      'depend',
      'fluent but insincere and shallow',
      'an obvious remark',
      'assistance and support in times of hardship and distress',
      'superficial(here)',
      'bringing strong images, memories or feelings to mind',
      'having a strong and exhilarating effect',
      'make one feel very happy, animated, or elated',
      'ecstatically happy',
      'feeling or expressing overwhelming happiness and excitement',
      'denoting a period of time in past that was happy',
      'growth or increase by gradual accumulation of additional layers or matter',
      'emphasize',
      'waste ina  reckless and foolish manner',
      'inquiring closely into something',
      'quality ofbeing clever, original and inventive',
      'showing dedication and diligence',
    ],
    count: 30,
  },
  page21: {
    words: [
      'incarnation',
      'axiomatic',
      'endemic',
      'contend',
      'surmount',
      'unviable',
      'archaic',
      'vestige',
      'nascent',
      'evanescent',
      'rebuttal',
      'rebut',
      'heinous',
      'odious',
      'quip',
      'witty',
      'quiver',
      'betray',
      'interminable',
      'hyperbolical',
      'qualify',
      'maintain',
      'incisive',
      'culminate',
      'decisive',
      'mawkish',
      'concede',
      'engender',
      'perfidy',
    ],
    meanings: [
      'each of a series of earthly lifetimes',
      'self-evident or unquestionable',
      'native to',
      'struggle to overcome',
      'overcome',
      'not capable of working successfully',
      'very old fashioned',
      'smallest amount',
      'just coming into existence and displaying future potential',
      'soon passing out of sight, memory or existence',
      'an instance of proving an evidence to be false',
      'claim or prove something to be false',
      'utterly unpleasant and wicked',
      'extremely unpleasant; repulsive',
      'make a witty remark',
      'showing quick and innovative verbal humour',
      'tremble or shake with slight rapid motion',
      'to reveal or make known something; usually unintentionally',
      'endless or apparently endless',
      'deliberately exaggerated',
      'make less severe; to limit',
      'make sure of',
      'having or demonstrating ability to recongize and draw fine distinctions',
      'reach the highest or climax or most decisive point',
      'settling an issue; able to make decisions quickly and effortlessly',
      'very sentimental to the point that it is disgusting',
      'acknowledge defeat or surrender',
      'give rise to',
      'an act of deliberate betrayal',
    ],
    count: 29,
  },
  page22: {
    words: [
      'preclude',
      'banal',
      'torpor',
      'vigor',
      'glut',
      'dogmatic',
      'aesthetic',
      'mitigate',
      'gall',
      'impertinent',
      'pertinent',
      'apt',
      'apposite',
      'querulous',
      'predilection',
      'obscure',
      'gainsay',
      'chortle',
      'recondite',
      'lmabast',
      'culpability',
    ],
    meanings: [
      'prevent from happening; make impossible',
      'overfamiliar through overuse',
      'inactivity resulting from lethargy, and lack of vigor or energy',
      'physical strength and good health',
      'an excessive supply',
      'highly opinionated, not accepting ones own belief may not be correct',
      'concerned with the appreciation of beauty',
      'make less severe or harsh',
      'trait of being rude and impertinent',
      'not showin proper respect; rude',
      'relevant or appreciable to a particular matter',
      'suitable',
      'apt',
      'habitually complaining',
      'strong liking',
      'make unclear',
      'deny or contradict',
      'to chuckle, laugh merrily, often in a breathy muffled way',
      'incomprehensible to one of ordinary understanding',
      'criticize severly or angrily',
      'a state of guilt',
    ],
    count: 21,
  },
  page23: {
    words: [
      'aesthete',
      'inexorable',
      'rustic',
      'provincial',
      'audacious',
      'bucolic',
      'superfluous',
      'prescience',
      'apathetic',
      'dictatorial',
      'impudent',
      'gossamer',
      'trite',
      'glean',
      'vicarious',
      'proselytize',
      'ethereal',
      'faddish',
      'ordinance',
      'hubbub',
      'dearth',
      'curb',
      'condone',
      'flustere',
    ],
    meanings: [
      'one who professes great sensitivity to the beauty of art and nature',
      'impossible to stop or prevent',
      'characteristic os rural life; awkardly simple and provincial',
      'belonging to a province',
      'willing to be bold in social situations or to take risks',
      'relating to the pleasant aspects of the country',
      'serving no useful purpose',
      'power to foresee the future',
      'marked by a lack of interest',
      'expecting unquestioning obedience; charactersitic of an absolute ruler',
      'imporpoerly forward and bold',
      'characterized by unusual lightness and delicacy',
      'dull on account of overuse',
      'obtain with difficulty',
      'experienced in the imagination through feelings of another person',
      'advocate or promote a belief',
      'relating to heavenly or spiritual',
      'no real value',
      'an authorative order',
      'noisy situation',
      'scarcity or lack of something',
      'restrain or keep in check',
      'accept something that is normally considered wrong',
      'make someone agitated or confused',
    ],
    count: 24,
  },
  page24: {
    words: [
      'reconcile',
      'clutch',
      'vitrolic',
      'malice',
      'diplomatic',
      'complacent',
      'convivial',
      'haphazard',
      'sedulous',
      'scrupulous',
      'inadvertently',
      'pristine',
      'imperil',
      'illuminate',
      'contrivance',
      'prevalent',
      'veneer',
      'jockey',
      'estimable',
      'machinate',
      'muckracking',
      'benign',
      'menacing',
      'innocuous',
      'resolute',
      'assidiuous',
      'industrious',
    ],
    meanings: [
      'settle an issue or accept',
      'get hold of something',
      'filled with bitter, criticism, or malice',
      'desire to harm someone',
      'quality of dealing with people in a sensitive and tactful way',
      'showing smug or uncritical satisfaction with ones own achievements',
      'friendly, enjoyable',
      'lacking an obvious principle or organization',
      'showing dedication and diligence',
      'careful, thorough, and extremely attentive to details',
      'accidentally',
      'unspoilt, clean and fresh, untouched',
      'put at risk of being harmed, inured or destroyed',
      'help to clarify or explain',
      'use of skill to create something, especially with a consequent effect of artificiality',
      'widespread in a particular area/time',
      'an attractive appearance that disguises something or someones true nature',
      'struggle by every means to achieve something',
      'worthy of great respect',
      'engage in plots; scheme',
      'action of searching out and publicizing scandal about famous people',
      'gentle and kind; not harmful',
      'suggesting presence of danger',
      'not hamrful or offensive',
      'determined',
      'showing great care and perseverance',
      'diligent and hard-working',
    ],
    count: 27,
  },
  page25: {
    words: [
      'turbulent',
      'mendacious',
      'despots',
      'malign',
      'personable',
      'munificient',
      'nugatory',
      'ersatz',
      'clandestine',
      'illicit',
      'ingenuity',
      'solipsism',
      'sophomoric',
      'quixotic',
      'arresting',
      'undue',
      'unwarranted',
      'ran the gauntlet',
      'ran the gamut',
      'ape',
    ],
    meanings: [
      'characterized by conflict, disorder or confusion; not stable or calm',
      'lying',
      'a person who holds absolute power, typically one who exercises it in a cruel way',
      'evil nature or effect',
      'pleasant appearance and manner',
      'displaying great generousity',
      'of no value or importance',
      'not real or genuine',
      'kept secretely or done secretely, especially because illegal',
      'illegal',
      'quality of being clever, original and inventive',
      'a view or theory that the self is all that can be known to exist',
      'relating to characteristic of a sophomore',
      'extremely idealistic, unrealistic, impractical',
      'striking, shocking, eye-catching',
      'inappropriate because excessive or disproportionate',
      'not justified or authorized',
      'go through an intimidating or dangerous crowd to reach a goal',
      'to encompass an entire range of something',
      'imitate',
    ],
    count: 20,
  },
  page26: {
    words: [
      'cabal',
      'clique',
      'literati',
      'hoi-polloi',
      'dulcet',
      'facile',
      'urbane',
      'painstaking',
      'fawning',
      'fawn',
      'erudite',
      'baneful',
      'presumptuous',
      'noxious',
      'patronizing',
      'condescending',
      'stolid',
      'whimsical',
      'quaint',
      'officious',
      'overstrip',
      'faculty',
    ],
    meanings: [
      'a secret political clique or faction',
      'a small close knit group of people who do not readily allow others to join them',
      'well educated people interested in literature',
      'the masses; common people',
      'sweeth and soothing',
      'ignoring true complexities of an issue; easily achieved, effortless',
      'courteous and refined in manner',
      'done with or employing great care and thoroughness',
      'displaying exaggerated flattery or affection',
      'to produce young',
      'having or showing great knowledge or learning',
      'harmful and destructive',
      'failing to observe the limits of what is permitted ot appropriate',
      'harmful, poisonous or unpleasant',
      'apparently kind or helpful but betraying effect of superiorty',
      'having or showing patronized superiority',
      'calm, dependable, showing little emotion',
      'playfully old-fashioned or fanciful',
      'old-fashioned',
      'assertive of authority in a domineering way',
      'overtake',
      'an inherent mental or physical power',
    ],
    count: 22,
  },
  page27: {
    words: [
      'poultice',
      'inflammation',
      'foible',
      'mores',
      'peccadillo',
      'vivacity',
      'garish',
      'obtrusive',
      'lurid',
      'perusal',
      'lexicon',
      'advent',
      'akin',
      'assain',
      'elitist',
      'elite',
      'misogynist',
      'kerfuffle',
      'pragmatic',
      'acclimate',
    ],
    meanings: [
      'soft, moist mass of material typically herbs placed on bofy to relieve soreness, inflammation',
      'a localized part of body which is reddened, lumpred, painful',
      'a minor weakness or strangenes in someones character',
      'essential or charactersitic custom and convention of a society or community',
      'a relatively minor fault or sin',
      'quality of being attractively lively and animated',
      'obstrusively bright and showy',
      'noticeable or prominent in vividly shocking terms',
      'unpleasantly bright in color',
      'action of reading or examining something',
      'vocabulary of a person',
      'arrival of a notable person or thing',
      'similar character',
      'make a violent attack',
      'having a view that a society should be led by an elite',
      'select group of people superior in terms of ability, or qulities to rest of the group or society',
      'person who dislikes, despises or is strongly prejudiced against women',
      'a commotion, especially one caused by conflicting views',
      'dealing with things sensibly and realistically in a way that is practical',
      'respond physiologically or behaviorally to a change in environmental factor under controlled conditions',
    ],
    count: 20,
  },
  page28: {
    words: [
      'unrepentant',
      'terraform',
      'wilt',
      'venture',
      'tutelage',
      'unnerving',
      'disconcerting',
      'amiable',
      'enigma',
      'assimilate',
      'contentious',
      'infuriate',
      'ominous',
      'pragmatist',
      'loom',
      'indictment',
      'miscreant',
      'epicentre',
      'peddling',
      'peddle',
    ],
    meanings: [
      'showing no regret for ones wrongdoings',
      'transforma planet so as to resemble earth; especially one that can support life',
      'less energy, vigor or confidence',
      'a risky or daring journey or undertaking; a business enterprise',
      'guardianship',
      'causeing one to lose courage or confidence; disconcerted',
      'causing one to feel unsettled',
      'having or displaying a friendly and unpleasant manner',
      'a person or thing that is mysterious and difficult to understand',
      'take in and unserstand fully',
      'causing or likely to cause an argument',
      'making someone extremely angry or impatient',
      'giving the worrying impression that something bad is going to happen',
      'a person who is guided more by practical considerations than by ideas',
      'appear as a vague form; especially one that is large or threatening',
      'a formal charge/accusation of a serious crime',
      'a person who has done something wrong or unlawful',
      'a point on earths surface vertically above the focus of an earthquake',
      'action of promoting an idea or view, persistently and widely',
      'try to sell something by going from place to place',
    ],
    count: 21,
  },
  page29: {
    words: [
      'snark',
      'confidant',
      'unhinged',
      'ergonomic',
      'conundrum',
      'rudimentary',
      'coital',
      'obnoxious',
      'plucky',
      'pensive',
      'ajar',
      'caveat',
      'diabolical',
      'profane',
      'weary',
      'berserk',
      'forlorn',
      'purview',
      'delirium',
      'ghoul',
    ],
    meanings: [
      'an imaginary animal, used typically with reference to a task that is elusive or impossible to achieve',
      'a person with whom one shares a secret or private matter, in trust it doesnt get gossiped',
      'mentally unbalanced; deranged',
      'related to or designated for efficiency and comfort in the working environment',
      'a confusing and difficult problem or question; a question usually asked for amusement, a riddle',
      'limited to basic principles',
      'relating to sexual intercourse',
      'extremely unpleasant',
      'having or showing detemrined courage in face of difficulties',
      'engaged in involving, or reflecting deep or serious thought',
      'slightly open',
      'a warning of specific stipulations, conditions, or limitations',
      'disgracefully bad or unpleasant; characteristics of a devil',
      'not respectful of religious practice',
      'feeling or showing extreme tiredness',
      'out of control with anger or excitement',
      'abandoned, sad and lonely',
      'range os experience or thought',
      'an acutely disturbed state of mind characterized by restlesness; typically during fever',
      'an evil spirit or phantom especially one supposed to rob graves; person morbidly interested in death and disasters',
    ],
    count: 20,
  },
  page30: {
    words: [
      'morbid',
      'appeal',
      'betwixt',
      'segue',
      'whirlwind',
      'derail',
      'gnawing',
      'skid',
      'raving',
      'shambles',
      'regale',
      'abyss',
      'chasm',
      'existential',
      'revive',
      'eldritch',
      'sinister',
      'opaue',
      'contingent',
    ],
    meanings: [
      'characterized by abnormal and unhea;thy interest in disturbing and unpleasant subjects; especially death and disease',
      'make a serious, urgent or heratfelt request',
      'between',
      'move or shift from one role, state, condition to another',
      'used with reference to a very energetic person',
      'diverting from its original course',
      'persistently worrying or distressing',
      'slide or slip',
      'irrational and incoherent talk',
      'a state of total disorder',
      'entertain or amuse with talk',
      'deep or seeminglt bottomless chasm; bottomless pit in hell',
      'profound difference between people, viewpoints, feelings',
      'relating to existence',
      'restore life or consciousness',
      'weird and sinister or ghostly',
      'an impression that something evil is happening or will happen',
      'not clearly understood or expressed',
      'a gathering of representatives of some larger group',
    ],
    count: 19,
  },
  page31: {
    words: [
      'apportion',
      'hysteria',
      'stigmatize',
      'demonize',
      'deify',
      'annotate',
      'abridge',
      'curtail',
      'antedate',
      'complementary',
      'complimentary',
      'excise',
      'levy',
      'expatriate',
      'yearn',
      'lascivious',
      'epoch',
      'posit',
      'preposterous',
      'indemnify',
      'musing',
      'actuary',
      'actuarial',
      'quotidian',
      'mundane',
      'caustic',
      'hysterical',
      'progeny',
      'lackadaiscal',
    ],
    meanings: [
      'divide up and share out',
      'exaggerated or uncontrollable emotion or excitement',
      'describe or regard as worthy of disgrace or disapproval',
      'portray as wicked or threatening',
      'worship or regard as god',
      'add notes to five explanation; commenting',
      'shorten without losing sense',
      'reduce in extent or quantity',
      'precede in time, come before in a date',
      'combining in such a way as to enhance or emphasize qualities of each other',
      'expressing a compliment',
      'remove from a text or piece of music; tax imposed on goods',
      'impose',
      'a person who lives outside their native country',
      'having an intense feeling of longing for something',
      'feeling ro revealing an overt sexual desire',
      'a particular period of time in history or a persons life',
      'put ofrward as a fact or basis for argument',
      'contrary to reason or common sense',
      'compensate for harm and loss',
      'a period od reflection or thought',
      'a person who compiles and analyses statistics to calculate risks and premiums',
      'relating to works of an actuary',
      'occuring every day',
      'lacking interest or excitement',
      'sarcastic in a scathing and bitter way',
      'affected by or deriving from wildly uncontrolled emotion',
      'a descendant',
      'lacking enthusiasm and determination; carelessly lazy',
    ],
    count: 29,
  },
  page32: {
    words: [
      'serendipity',
      'akimbo',
      'abreast of',
      'obtuse',
      'subservient',
      'askance',
      'proponent',
      'apologist',
      'mercenary',
      'demarcate',
      'whitewash',
      'improvident',
      'dissolute',
      'sensual',
      'catapult',
      'hurl',
      'impel',
      'pallid',
      'impecunious',
      'aghast',
      'virtue',
      'utilitarian',
      'emulate',
      'enshrine',
      'receptacle',
    ],
    meanings: [
      'occurence and development of events by chance in a happy and beneficial way',
      'flung out widely or haphazardly',
      'stay or cause to stay up to date with',
      'annoyingly insensitive or slow to understand',
      'prepared to obey others unuestioningly',
      'with an attitude or look of suspicon of disapproval',
      'a person who advocates a theory, proposal or course of action',
      'a person who offers an argument in defence of something controversial',
      'primarily concerned with making money at expense of others; a professional soldier hired to serve in a foreign army',
      'set boundaries or distinguish',
      'brainwash',
      'no foresight; thoughtless',
      'overindulging in sensual pleasures',
      'relating to senses, physically, and even sexual pleasure',
      'hult or launch',
      'throw or impel with great force',
      'urge to do something',
      'lacking vigor or intensity',
      'having little or no money',
      'filled with horror or shock',
      'behavior showing high moral standards',
      'designed to be useful or practical rather than attractive',
      'match, typically by imitation',
      'preserve',
      'a hollow object to contain something; box',
    ],
    count: 25,
  },
  page33: {
    words: [
      'enigmatic',
      'emblematic',
      'grandiloquent',
      'pompous',
      'cajole',
      'coax',
      'solemn',
      'roundly',
      'emphatic',
      'lauded',
      'panned',
      'insouicance',
      'profundity',
      'wracked',
      'strife',
      'prologue',
      'catharsis',
      'coda',
      'rampage',
      'anachronism',
      'providential',
      'shrewd',
      'simpatico',
      'exempted',
      'effusive',
      'maudlin',
      'husband',
      'steward',
      'upend',
      'fickle',
      'vacillate',
      'waver',
    ],
    meanings: [
      'difficult to interpret or understand',
      'serving as a symbol of a particulat quality or concept',
      'pompous or extravagant in language, style or manner to impress',
      'grand; self-important',
      'persuade to do something by flattery',
      'gentle persuasion',
      'formal and dignified',
      'in a vehement manner',
      'expressing something forcibly and clearly',
      'highly praised or admired',
      'criticize severly',
      'casual lack of concern',
      'great depth of insight',
      'cause extreme pain',
      'conflict',
      'an event or act that leads to another',
      'process of releasing and thereby providing relief from repressed emotions',
      'a concluding event, remark or section',
      'move through a place in a violent manner',
      'action of attributing something to a period of time to which it doesnt belong',
      'occuring at a favorable time; opportune',
      'showing sharp powers of judgement',
      'characterized by shared attributes of interests; compatible',
      'free from an obligation or liability imposed on others',
      'showing gratitude or approval in an unrestrained or heartfelt manner',
      'highly sentimental',
      'use reources economically',
      'manage or look after resources',
      'upside down',
      'changing frequently; especially in regards to ones loyalties or affections',
      'waver between different opinions',
      'flicker between two opinions',
    ],
    count: 33,
  },
  page34: {
    words: [
      'fledgling',
      'torpid',
      'lithe',
      'supple',
      'critique',
      'tirade',
      'panacea',
      'gloss',
      'flagging',
      'hale',
      'lissom/lissome',
      'loathsome',
      'melange',
      'medley',
      'paucity',
      'tacit',
      'implicit',
      'lax',
      'priggish',
      'impious',
      'punctillious',
      'self-righteous',
      'tout',
      'partisan',
      'prejudice',
      'somber',
      'philander',
      'prurient',
      'wry',
    ],
    meanings: [
      'a person or organization that is unexperienced',
      'mentally or physically inactive',
      'thin, supple and graceful',
      'wasily manipulated; flexible',
      'a detailed assessment',
      'a long angry speech',
      'solution or remedy for all difficulties and diseases',
      'provide an explanation',
      'become tired; declining in strength',
      'strong and healthy',
      'lithe',
      'causing hatred or disgust, repulsive',
      'a varied mixture',
      'a varied mixture',
      'presence of something in insufficient quantitites',
      'undestood or implied without being stated',
      'not sufficiently strict, severe, or careful',
      'self-righteously superior or moralistic',
      'showing lack of respect for god and religion',
      'showing great atention to detail or correct behavior',
      'characterized by certainity, totally correct',
      'attempt to sell by a persistent approach',
      'prejudiced in favor of a particular cause',
      'preconceived opinion that is not based on reason or actual experience',
      'feeling of deep seriousness and sadness',
      'frequently entering into casual sex with women',
      'playful, in a mischevious way',
      'encouraging interest in sex, especially of others',
      'using mocking humor',
    ],
    count: 29,
  },
  page35: {
    words: [
      'puritancial',
      'dire',
      'presage',
      'recession',
      'endeavour',
      'unpropitious',
      'solvent',
      'uptick',
      'virulence',
      'bestow',
      'confer',
      'bevy',
      'marshal',
      'obligate',
      'ex post fact',
      'remission',
      'juxtapose',
      'escapade',
      'acclaim',
      'contrive',
      'vehement',
      'vilify',
      'avaricious',
      'ecelctic',
      'forlorn',
      'haughty',
      'ascetic',
      'elucidate',
      'panache',
      'refractory',
      'fanitical',
      'zeal',
      'treachareous',
    ],
    meanings: [
      'displaying a strict morral attitude towards sex',
      'extremely serious or urgent; presaging disaster',
      'warning',
      'action of receeding',
      'attempt to achieve a goal',
      'not indicating a good chance of success; unfavorable',
      'able to pay ones debts; having excess of assets',
      'small increase or slight upward trend',
      'bitter hostility; severity of a disease or poison',
      'present or confer',
      'grant',
      'a large group of people or things',
      'assemble and arrange',
      'require or compel someone to take a legal and moral duty',
      'retrospectively',
      'cancelation of a debt, charge or penalty',
      'place or deal with close together for contrasting effect',
      'an act involving excitement, adventure',
      'praise enthusiastically and publicly',
      'to pull off a plan or scheme, usually through skill or trickery',
      'marked by extreme intensity of emotions or convictions',
      'spread negative information about',
      'excessively greedy',
      'comprised of variety of styles',
      'marked by or showing hopelesness',
      'having or showing arrogant superiority to and disdain those views as unworthy',
      'practicing self-denial',
      'make clearer and easier to understand',
      'distinctive and showy elegance',
      'stubbornly resistant to authority or control',
      'filled with excessive single minded zeal',
      'great energy or enthusiasm in pursuit of a cause or objective',
      'tending to betray',
    ],
    count: 33,
  },
  page36: {
    words: [
      'frustrate',
      'precocious',
      'subsume',
      'quotidian',
      'disaffected',
      'discontent',
      'immutable',
      'staunch',
      'eminent',
      'languid',
      'heretic',
      'abstain',
      'guileless',
      'deceit',
      'spurious',
      'itinerant',
      'delineate',
      'travesty',
      'placate',
      'discrete',
      'intransigent',
      'decorum',
      'exonerate',
      'bumbling',
      'unceremonious',
      'impervious',
      'indifference',
      'implacable',
      'forthcoming',
      'ignoble',
      'expound',
      'exacting',
      'construe',
    ],
    meanings: [
      'hinder or prevent',
      'characteristic of an exceptionally early development or maturity',
      'contain or include',
      'found in ordinary course of events',
      'dissatidfaction towards authority',
      'dissatisfaction',
      'not able to change',
      'firm and dependable, especially in loyalty',
      'standing above others in quality or position',
      'not inclined towards physical exertion or effort; slow and relaxed',
      'a person who holds unorthodox opinions in any field',
      'choose not to consume or take part in',
      'free or deceit',
      'action of deceiving someone by misrepresenting truth',
      'plausible but false',
      'traveling from place to place for work',
      'explain in detail',
      'an absurd representation of something',
      'constituting a separate entity or part',
      'unwilling to change ones belief or course of actions',
      'propriety in manners and conduct',
      'pronounce not guilty of criminal charges',
      'lacking physical movement skills, especially with hands',
      'showing lack of courtesy',
      'impervious to correction by punishment',
      'inured',
      'trait of seeming not to care',
      'incapable of making less angry or hostile',
      'at ease in talking to others',
      'dishonorable',
      'add details or explanations; clarify the meaning',
      'requiring and demanding accuracy',
      'interpreted in a particular way',
    ],
    count: 33,
  },
  page37: {
    words: [
      'aberrant',
      'denigrate',
      'petulant',
      'soporific',
      'myopic',
      'ingratiate',
      'laudable',
      'admonitory',
      'reproof',
      'espouse',
      'idiosyncrasy',
      'exalt',
      'confound',
      'unscrupulous',
      'scruples',
      'pundit',
      'opaque',
      'largess',
      'refute',
      'iconoclastic',
      'tortuous',
      'dillentante',
      'pedestrian',
      'unfathomable',
      'admonish',
      'myriad',
      'arbitrary',
      'prolific',
      'ravenous',
      'pernicious',
      'winsome',
      'sanction',
    ],
    meanings: [
      'markedly different from an accepted norm',
      'charge falsely or with malicious intent',
      'easily irritated or annoyed',
      'sleep inducing',
      'lacking foresight and imagination',
      'gain favor with somebody by deliberate efforts',
      'worthy of high praise',
      'serving to warn; expressing reproach especially as a corrective',
      'an expression of blame or disapproval',
      'adopt or support an idea or cause',
      'a behavior attribute that is distinctive and peculiar to an individual',
      'praise or glorify',
      'to cause confusion',
      'without principles',
      'doubt or hesitation with regards to course of action',
      'someone who has been admitted membership to a scholarly field',
      'not clearly understood or expressed',
      'extreme generosity and giving',
      'prove to be false or incorrect',
      'defying tradition or convention',
      'not straightforward; repeated bends and turns',
      'an amateur who engages in an activity without seious intentions and who pretends to have knowledge',
      'lacking imagination',
      'incapable of being fully explored or understood',
      'to warn strongly, even to the point of reprimanding',
      'a large indefinite number',
      'based on a random, groundless decision',
      'intellectually productive',
      'extremely hungry, craving food in great quantitites',
      'insidious, in a hidden and injurious way',
      'charming in a child like or naive way; Katy perry in How I met your mother',
      'give authority or permission to; a legal penalty for a forbidden action',
    ],
    count: 32,
  },
  page38: {
    words: [
      'rescind',
      'constituent',
      'brazen',
      'subversive',
      'foment',
      'tempered',
      'moderated',
      'munificent',
      'inveterate',
      'austere',
      'unadorned',
      'poignant',
      'repudiate',
      'accolade',
      'garrulous',
      'hegemony',
      'precipitous',
      'haste',
      'insolent',
      'gauche',
      'resurgent',
      'irrevocable',
      'pedestrian',
      'vaccilate',
      'arcane',
      'dispassionate',
      'appease',
      'acceding',
      'pejorative',
    ],
    meanings: [
      'cancel officially',
      'a citizen who is represented in a government by officials for whom the person votes',
      'bold and without shame; unrestrained by convention',
      'in opposition to an established system or institution',
      'try to stir up public opinion',
      'moderated in effect',
      'become less extreme',
      'very generous',
      'habitual',
      'practicing self-denial',
      'plain',
      'emotionally touching',
      'reject as untrue or unfounded',
      'accolade',
      'full of trivial conversation',
      'dominance over a certain area',
      'done with great haste and without due deliberation',
      'hurry',
      'rude and arrogant',
      'lacking social polish',
      'rising again as to new life and vigor',
      'incapable of being retracted or revoked',
      'lacking imagination',
      'be undecided about something; waver between options',
      'requiring secret or mysterious knowledge',
      'unaffected by strong emotion or prejudice',
      'pacify by acceding to the demands of',
      'agree to a demand or request',
      'expressing disapproval',
    ],
    count: 29,
  },
  page39: {
    words: [
      'dilatory',
      'maladroit',
      'imprudent',
      'opulence',
      'capricious',
      'stringent',
      'deleterious',
      'furtive',
      'ignominious',
      'sullen',
      'antipathy',
      'harried',
      'placate',
      'esoteric',
      'nuance',
      'arduous',
      'maverick',
      'timorous',
      'banality',
      'rebuke',
      'contrition',
      'efficacious',
      'nonplussed',
      'duress',
      'jovial',
      'flux',
      'craven',
      'specious',
    ],
    meanings: [
      'wasting time',
      'clumsy',
      'not wise',
      'wealth as evidenced by sumptuous living',
      'determined by chance or impulse rather than by necessity or reason',
      'demanding strict attention to rules and procedures',
      'harmful to living things',
      'marked by quiet and caution and secrecy; taking pains to avoid being observed',
      'deserving or bringing disgrace or shame',
      'showing a brooding ill humor',
      'an intense feeling of dislike or aversion',
      'troubled persistently especially with petty annoyance',
      'cause to be more favorably inclined; gain the good will of',
      'confined to an understandable only to an enlightened inner circle',
      'a subtle difference in meaning or opinion or attitude',
      'demanding considerable mental effort and skill; testing powers of endurance',
      'someone who exhibits great independence in thoughts and action',
      'timid by nature or revealing fear and nervousness',
      'an obvious remark',
      'criticize severly or angrily; censure',
      'feeling of remorse or guilt that comes from doing something bad',
      'producing the intended result',
      'unsure how to act or respond',
      'compulsory force or threat',
      'showing high-spirited merriment',
      'state of uncertainity about what should be done',
      'pathetically cowardly',
      'plausible but false',
    ],
    count: 28,
  },
  page40: {
    words: [
      'mendacity',
      'askance',
      'profuse',
      'erratic',
      'zentih',
      'serendipity',
      'thoroughgoing',
      'vindictive',
      'embroiled',
      'demur',
      'inflammatory',
      'affluent',
      'reprobate',
      'bleak',
      'unnerve',
      'candid',
      'miser',
      'retiring',
      'slapdash',
      'underwrite',
      'hound',
      'voracious',
      'dog',
      'screed',
      'dupe',
      'swindle',
      'pine',
      'demean',
      'spendthrift',
      'telltale',
      'acme',
      'telling',
    ],
    meanings: [
      'tendency to be untruthful',
      'with a leak of suspicion or disapproval',
      'plentiful; pouring out in abundance',
      'unpredictable; strange and unconventional',
      'culmination',
      'instance in which an accidental, fortunate discovery is made',
      'very thorough; complete',
      'to have a very strong desire for revenge',
      'involved in argument or contention',
      'to be modest and shy',
      'extremely controversial; incendiary',
      'wealthy',
      'a person without morals who is disapproved of',
      'having a depressing or gloomy outlook',
      'to make nervous or accept',
      'straightforward and honest',
      'person who doesnt like to spend money',
      'to be shy, be inclined, retract from company',
      'carelessly and hastily put together',
      'to support financially',
      'to pursue relentlessly',
      'very hungry; approaching an activity with enthusiasm',
      'pursue relentlessly',
      'an abusive rant',
      'to trick',
      'a fraudulent scheme or action',
      'to yearn for',
      'to insult; cause someone to lose dignity and respect',
      'person who spends money extravagantly',
      'revealing',
      'highest point of achievement',
      'significant and revealing of another factor',
    ],
    count: 32,
  },
};
